### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by olegabr** [airevent/spaceship3000#1]
Ко мне в проекте на https://freelance.ru/ подался разработчик https://freelance.ru/marsgpl и дал ссылку на этот репозиторий как пример своего кода.
При этом настораживает полностью нулёвый аккаунт на https://freelance.ru/.
Пишу здесь чтобы спросить, действительно ли это ваш аккаунт https://freelance.ru/marsgpl, или какой-то мошенник использует ваш репозиторий чтобы придать себе значимости.
Извиняюсь если не к месту.

**Comment by airevent** [comment]
Да, это действительно мой аккаунт)

15 мая 2017 г., 21:08 пользователь Oleg Abrosimov <notifications@github.com>
написал:
